services:
  - type: web
    name: user-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - key: PORT
        value: 8080
